name: Docker CD

# Every time the repo updates, make a new Docker image.
on:
  push:
# You may want to do this per day instead though:
# on:
#  schedule:
#    - cron: $cron-daily
# Or per merged pull request (a hassle: https://github.com/orgs/community/discussions/26724 )


jobs:
  docker:

    # Set the OS that this workflow runs on.
    runs-on: ubuntu-latest

    # Initialise environment variables to be edited during the workflow. 
    env: 
      OWNER_LC: ""
      REPO_LC: ""

      # Packages (Docker images) must be writable. 
      # Contents (repo files & folders) must be readable.
    permissions: 
      packages: write
      contents: read
    steps:
      # If we wanna publish to Docker Hub, use this. We can publish to multiple places simultaneously!
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ vars.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Uppercase names in repos or GitHub usernames breaks things sometimes. 
    # So, make a lowercase (LC) copy of some key data.
      - name: Sanitise metadata for Docker container publishing
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
          REPO: '${{ github.repository }}'

          # GITHUB_TOKEN is automatically made by GitHub.
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # Beneficial for Docker image building:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
        # Required for Docker image building:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Required for Docker image publishing:
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}:latest
            ghcr.io/${{ env.REPO_LC }}:1.0.0